version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    volumes:
      - ./model_pickle_files:/app/model_pickle_files
    ports:
      - "8080:8080"
    depends_on:
      - redis

  redis:
    image: redis
    volumes:
      - ./data:/data
